---
- hosts: ios
  gather_facts: no

  tasks:
  
  - name: CONFIGURE
      ios_config:
        lines:
          - file prompt quiet

  - name: SHOW RUN | BEG BANNER 
    ios_command:
      commands:
        - copy running-config startup-config
    #register: banner

  #- debug: var=banner.stdout_lines
