---
- hosts: ios
  gather_facts: no

  tasks:
  
 - name: NO SERVICE PAD 
    ios_config:
      lines:
        - no service pad

  - name: IP SSH VERSION 2 
    ios_config:
      lines:
        - ip ssh version 2

  - name: CONFIGURE
      ios_config:
        lines:
          - file prompt quiet

  - name: SHOW RUN | BEG BANNER 
    ios_command:
      commands:
        - copy running-config startup-config

