---
- hosts: ios
  gather_facts: no


  tasks:
 
  - name: no file prompt
    ios_config:
      lines:
        - file prompt quiet

  - name: SAVE CONFIG 
    ios_command:
      commands:
        - copy running-config startup-config